### ISSUE TITLE
Add this Template feature

### ISSUE THREAD

**Issue by lfarah** [awesome-labs/iOS-readme-template#2]
https://github.com/hyperoslo/SwiftPackage/commit/d6e82ca021d2bf27bdef52a20f1c32f045337b3d

**Comment by lfarah** [comment]
Hey @onmyway133, can you help us with this?

**Comment by onmyway133** [comment]
@lfarah I 'd suggest moving Release History into its own file, so that to avoid making README too long

**Comment by lfarah** [comment]
@onmyway133 definitely makes sense!
